const ADD_CLIP = 'ADD_CLIP';
const ADD_TRACK_TO_TABLE = 'ADD_TRACK_TO_TABLE';
const REMOVE_TRACK_FROM_TABLE = 'REMOVE_TRACK_FROM_TABLE';
const ADD_CLIP_TO_TRACK = 'ADD_CLIP_TO_TRACK';

export default {
  ADD_CLIP,
  ADD_TRACK_TO_TABLE,
  REMOVE_TRACK_FROM_TABLE,
  ADD_CLIP_TO_TRACK
};
