const UPDATE_CLIP = 'UPDATE_CLIP';
const DECREMENT_TRACKS = 'DECREMENT_TRACKS';
const INCREMENT_TRACKS = 'INCREMENT_TRACKS';
const ADD_TRACK = 'ADD_TRACK';
const REMOVE_TRACK = 'REMOVE_TRACK';
const ADD_CLIP_TO_TRACK = 'ADD_CLIP_TO_TRACK';
const ADD_CLIP_TO_MAP = 'ADD_CLIP_TO_MAP';
const DUPLICATE_CLIP = 'DUPLICATE_CLIP';
const DRAG_DUPLICATE_CLIP = 'DRAG_DUPLICATE_CLIP';
const DELETE_CLIP = 'DELETE_CLIP';
const MS_PER_PIXEL = 100;
const CLIP_MOVE_THROTTLE = 40;
const SLIDE_INTERVAL_TIME = 40;
const SLIDE_TIME = 500;
const RESIZE_THROTTLE = 10;
const GRID_SNAP_THRESHOLD = 0.5;

export default {
  UPDATE_CLIP,
  ADD_TRACK,
  REMOVE_TRACK,
  ADD_CLIP_TO_TRACK,
  MS_PER_PIXEL,
  ADD_CLIP_TO_MAP,
  CLIP_MOVE_THROTTLE,
  DUPLICATE_CLIP,
  DRAG_DUPLICATE_CLIP,
  SLIDE_INTERVAL_TIME,
  SLIDE_TIME,
  RESIZE_THROTTLE,
  DELETE_CLIP,
  GRID_SNAP_THRESHOLD
};
