const UPDATE_CLIP = 'UPDATE_CLIP';
const DECREMENT_TRACKS = 'DECREMENT_TRACKS';
const INCREMENT_TRACKS = 'INCREMENT_TRACKS';
const ADD_TRACK = 'ADD_TRACK';
const REMOVE_TRACK = 'REMOVE_TRACK';
const ADD_CLIP_TO_TRACK = 'ADD_CLIP_TO_TRACK';
const ADD_CLIP_TO_MAP = 'ADD_CLIP_TO_MAP';
const RESIZE_TABLE = 'RESIZE_TABLE';
const MS_PER_PIXEL = 100;
const CLIP_MOVE_THROTTLE = 40;
const SLIDE_INTERVAL_TIME = 40;
const SLIDE_TIME = 500;
const RESIZE_THROTTLE = 10;
const GRID_SNAP_THRESHOLD = 1000;

export default {
  UPDATE_CLIP,
  ADD_TRACK,
  REMOVE_TRACK,
  ADD_CLIP_TO_TRACK,
  MS_PER_PIXEL,
  ADD_CLIP_TO_MAP,
  CLIP_MOVE_THROTTLE,
  SLIDE_INTERVAL_TIME,
  SLIDE_TIME,
  RESIZE_THROTTLE,
  RESIZE_TABLE,
  GRID_SNAP_THRESHOLD
}
